services:
  - type: web
    name: packet-analyzer-backend
    runtime: python
    branch: main                           
    plan: starter                          
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    rootDir: backend              # ✅ Correct key (not workingDir)
    autoDeployTrigger: commit
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
